###############################################################################
# SilverBullet Libraries
###############################################################################

-include .env
export

.DEFAULT_GOAL := help

LIBRARIES := kanboard
SB_IMAGE ?= ghcr.io/silverbulletmd/silverbullet:latest
SB_CONTAINER ?= silverbullet-test
SB_HOST_PORT ?= 3000
KB_BASE_URL ?= https://kanboard.mydomain.com
KB_TOKEN ?= 5ec7e7
KB_USERNAME ?= me@mydomain.com
KB_PROJECT_ID ?= 1
# OPEN_COMMAND can be overridden on Linux with xdg-open
OPEN_COMMAND ?= open
TEST_SPACE_DIR ?= test/space
TEST_BUILD_DIR ?= test/build
TEST_TEST_DIR ?= test/test

# Release/versioning
RELEASE_MAJOR_FILE ?= RELEASE_MAJOR
RELEASE_MINOR_FILE ?= RELEASE_MINOR
RELEASE_PATCH_FILE ?= RELEASE_PATCH
RELEASE_DIR ?= releases
.PHONY: help all build clean test testspace release changelog $(LIBRARIES)

###############################################################################
# Build
###############################################################################

all: $(LIBRARIES)

kanboard:
	@echo "Building Kanboard..."
	@mkdir -p "$(TEST_BUILD_DIR)"
	@cat src/kanboard/frontmatter.md > "$(TEST_BUILD_DIR)/Kanboard.md"
	@printf "%s\n" \
		"> **note**" \
		"> This file is autogenerated by 'make'." \
		"> Edits should be made in the files under src/kanboard/." >> \
		"$(TEST_BUILD_DIR)/Kanboard.md"
	@cat src/kanboard/kanboard.md >> "$(TEST_BUILD_DIR)/Kanboard.md"
	@echo "" >> "$(TEST_BUILD_DIR)/Kanboard.md"
	@echo '```space-lua' >> "$(TEST_BUILD_DIR)/Kanboard.md"
	@cat src/kanboard/library.lua >> \
		"$(TEST_BUILD_DIR)/Kanboard.md"	
	@cat src/kanboard/kanboard.lua >> \
		"$(TEST_BUILD_DIR)/Kanboard.md"
	@echo "" >> "$(TEST_BUILD_DIR)/Kanboard.md"
	@echo '```' >> "$(TEST_BUILD_DIR)/Kanboard.md"
	@echo "Done."

###############################################################################
# Test
###############################################################################

test: all testspace
	@echo "Stopping any existing SilverBullet container..."
	@docker stop "$(SB_CONTAINER)" >/dev/null 2>&1 || true
	@echo "Starting SilverBullet in Docker..."
	@docker run --rm -d --name "$(SB_CONTAINER)" \
		-p $(SB_HOST_PORT):3000 \
		-v "$(CURDIR)/$(TEST_TEST_DIR):/space" \
		$(SB_IMAGE)
	@sleep 3
	@echo "Opening SilverBullet at http://localhost:$(SB_HOST_PORT)..."
	@$(OPEN_COMMAND) "http://localhost:$(SB_HOST_PORT)"

build: all

help:
	@printf "Finestream's SilverBullet Libraries:\n"	
	@printf "====================================\n\n"
	@printf "Available targets:\n"
	@printf "\nBuild:\n"
	@printf "  all\t\tBuild all libraries\n"
	@printf "  build\t\tAlias for all\n"
	@printf "\nTest:\n"
	@printf "  test\t\tPrepare the testspace, start SilverBullet in Docker,"
	@printf " and open it in a browser\n"
	@printf "  testspace\tPrepare the SilverBullet testspace and copy the\n"
	@printf "    built library into it\n"
	@printf "\nRelease and versioning:\n"
	@printf "  release\tPublish built libraries to the release directory\n"
	@printf "  bump-feature\tIncrement the feature version and reset patch\n"
	@printf "  bump-fix\tIncrement the patch version\n"
	@printf "\nMaintenance:\n"
	@printf "  clean\t\tStop the SilverBullet test container and remove\n"
	@printf "    generated test files\n"
	@printf "  help\t\tShow this help message\n"
	@printf "\nEnvironment vars:\n"
	@printf "  SB_HOST_PORT\tHost port for Docker port mapping (default: 3000)\n"
	@printf "  KB_BASE_URL\tKanboard base URL used in CONFIG.md\n"
	@printf "  KB_TOKEN\tKanboard token used in CONFIG.md\n"
	@printf "  KB_USERNAME\tKanboard username used in CONFIG.md\n"
	@printf "  KB_PROJECT_ID\tKanboard project ID used in CONFIG.md (default: 1)\n"
	@printf "  OPEN_COMMAND\tCommand to open the default browser (default: open)\n"
	@printf "  SB_IMAGE\tDocker image to run for SilverBullet\n"
	@printf "  SB_CONTAINER\tName for the SilverBullet Docker container\n"

testspace: all
	@echo "Preparing SilverBullet testspace..."
	@mkdir -p "$(TEST_TEST_DIR)"
	@mkdir -p "$(TEST_TEST_DIR)/Library/Finestream"
	@if [ -d "$(TEST_SPACE_DIR)" ]; then \
		cp -R "$(TEST_SPACE_DIR)/." "$(TEST_TEST_DIR)/"; \
	fi
	@cp "$(TEST_BUILD_DIR)/Kanboard.md" \
		"$(TEST_TEST_DIR)/Library/Finestream/Kanboard.md"
	@printf '%s\n' '```space-lua' > "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '%s\n' 'config.set {' >> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '%s\n' '  kanboard = {' >> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '      kbBaseUrl = "%s", -- Kanboard base URL\n' \
		"$(KB_BASE_URL)" \
		>> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '      sbBaseUrl = "%s", -- Silverbullet base URL\n' \
		"http://localhost:$(SB_HOST_PORT)" \
		>> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '      kbUsername = "%s", -- Kanboard username\n' \
		"$(KB_USERNAME)" \
		>> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '      kbToken = "%s", -- Kanboard token for username\n' \
		"$(KB_TOKEN)" \
		>> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '      kbProjectId = %s, -- default projectId in Kanboard\n' \
		"$(KB_PROJECT_ID)" \
		>> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '%s\n' '      sbCachePath = "Kanboard", -- Path on Silverbullet space for cache' \
		>> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '%s\n' '      sbCacheRefreshHours = 6, -- max cache age in hours' \
		>> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '%s\n' '      kbCloseDone = false, -- close done tasks when syncing status' \
		>> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '%s\n' '      kbMoveDone = true, -- move done tasks to the last Kanboard column when syncing status' \
		>> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '%s\n' '  }' >> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '%s\n' '}' >> "$(TEST_TEST_DIR)/CONFIG.md"
	@printf '%s\n' '```' >> "$(TEST_TEST_DIR)/CONFIG.md"
	@echo "Testspace ready at $(TEST_TEST_DIR)."

###############################################################################
# Release
###############################################################################

release: all
	@echo "Publishing libraries..."
	@major=$$(cat $(RELEASE_MAJOR_FILE) 2>/dev/null || echo 0); \
	minor=$$(cat $(RELEASE_MINOR_FILE) 2>/dev/null || echo 0); \
	patch=$$(cat $(RELEASE_PATCH_FILE) 2>/dev/null || echo 0); \
	ver=$$major.$$minor.$$patch; \
	if [ -f "$(RELEASE_DIR)/VERSION" ] && \
		[ "$$ver" = "$$(cat $(RELEASE_DIR)/VERSION)" ]; then \
		echo "Version $$ver already released in $(RELEASE_DIR)/VERSION"; \
		exit 1; \
	fi; \
	mkdir -p $(RELEASE_DIR)/Library/Finestream; \
	cp "$(TEST_BUILD_DIR)/Kanboard.md" \
		"$(RELEASE_DIR)/Kanboard.md"; \
	echo "$$ver" > "$(RELEASE_DIR)/VERSION"; \
	git tag -a "v$$ver" -m "Release $$ver" || echo "git tag failed (maybe already exists)"; \
	echo "Published to $(RELEASE_DIR)/Library/Finestream/Kanboard.md (VERSION=$$ver)"

.PHONY: bump-feature bump-fix

# bump-feature: increment Y (feature) and reset Z (patch)
bump-feature:
	@major=$$(cat $(RELEASE_MAJOR_FILE) 2>/dev/null || echo 0); \
	minor=$$(cat $(RELEASE_MINOR_FILE) 2>/dev/null || echo 0); \
	minor=$$((minor+1)); \
	echo $$minor > $(RELEASE_MINOR_FILE); \
	echo 0 > $(RELEASE_PATCH_FILE); \
	echo "Bumped feature to $$major.$$minor.0"

# bump-fix: increment Z (patch)
bump-fix:
	@patch=$$(cat $(RELEASE_PATCH_FILE) 2>/dev/null || echo 0); \
	patch=$$((patch+1)); \
	echo $$patch > $(RELEASE_PATCH_FILE); \
	major=$$(cat $(RELEASE_MAJOR_FILE) 2>/dev/null || echo 0); \
	minor=$$(cat $(RELEASE_MINOR_FILE) 2>/dev/null || echo 0); \
	echo "Bumped patch to $$major.$$minor.$$patch"

###############################################################################
# Clean
###############################################################################

# Clean removes the SilverBullet test container and deletes generated test
# directories so the environment is reset for the next run.
clean:
	@echo "Cleaning..."
	@docker rm -f "$(SB_CONTAINER)" >/dev/null 2>&1 || true
	@rm -rf test/build test/test
	@echo "Done."